version: '2.3'

services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    volumes:
      - saleor-db:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:5.0.2-alpine
    restart: unless-stopped
    volumes:
      - saleor-redis:/data
    ports:
      - 6379:6379

  search:
    image: elasticsearch:5.6-alpine
    restart: unless-stopped
    volumes:
      - saleor-search:/usr/share/elasticsearch/
    ports:
      - 9200:9200
    # See https://github.com/docker/compose/issues/4513 if updating to version '3'
    mem_limit: 512m
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.disable.jmx=true"

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-search:
    driver: local
